from PySide6.QtCore import QByteArray
from PySide6.QtWidgets import QWidget

class CDockManager:
    class eConfigFlag:
        OpaqueSplitterResize: int
        XmlCompressionEnabled: int
        AllTabsHaveCloseButton: int
        DockAreaHasCloseButton: int
        DockAreaHasUndockButton: int

    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @staticmethod
    def setConfigFlag(flag: int, enabled: bool) -> None: ...
    def saveState(self) -> QByteArray: ...
    def restoreState(self, data: QByteArray) -> bool: ...
    def addDockWidget(self, area: int, dock: CDockWidget) -> None: ...
    def deleteLater(self) -> None: ...

class CDockWidget:
    class DockWidgetFeature:
        DockWidgetClosable: int
        DockWidgetMovable: int
        DockWidgetFloatable: int
        DockWidgetDeleteOnClose: int

    def __init__(self, manager: CDockManager, title: str, parent: QWidget | None = ...) -> None: ...
    def setWidget(self, widget: QWidget) -> None: ...
    def setFeature(self, feature: int, enabled: bool) -> None: ...
    def setFloating(self) -> None: ...
    def isFloating(self) -> bool: ...
    def closeDockWidget(self) -> None: ...

LeftDockWidgetArea: int
RightDockWidgetArea: int
BottomDockWidgetArea: int
CenterDockWidgetArea: int
